-- Church treasury schema (PostgreSQL).
-- Nothing is ever hard-deleted: rows get deleted_at + delete_reason instead.
-- Money is stored as whole hundredths (500.50 -> 50050).
-- Dates and times are stored as ISO text (2026-10-03, 2026-10-03T08:00:00Z) so they sort correctly.

CREATE TABLE funds (
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE items (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fund_id       BIGINT NOT NULL REFERENCES funds(id),
  name          TEXT NOT NULL UNIQUE,
  system_key    TEXT UNIQUE,              -- OFFERING_TRUST / OFFERING_LOCAL for the split halves
  active        INTEGER NOT NULL DEFAULT 1,
  deleted_at    TEXT,
  delete_reason TEXT
);

CREATE TABLE subgroups (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id       BIGINT NOT NULL REFERENCES items(id),
  name          TEXT NOT NULL,
  active        INTEGER NOT NULL DEFAULT 1,
  deleted_at    TEXT,
  delete_reason TEXT,
  UNIQUE (item_id, name)
);

CREATE TABLE people (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL,
  deleted_at    TEXT,
  delete_reason TEXT
);

CREATE TABLE receipts (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_number INTEGER NOT NULL UNIQUE,  -- never reused, even after delete
  receipt_date   TEXT NOT NULL,            -- ISO yyyy-MM-dd
  person_id      BIGINT NOT NULL REFERENCES people(id),
  created_at     TEXT NOT NULL,
  deleted_at     TEXT,
  delete_reason  TEXT
);

CREATE TABLE receipt_lines (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receipt_id        BIGINT NOT NULL REFERENCES receipts(id),
  item_id           BIGINT NOT NULL REFERENCES items(id),
  subgroup_id       BIGINT REFERENCES subgroups(id),
  amount_hundredths BIGINT NOT NULL CHECK (amount_hundredths > 0),
  split_group       TEXT,                  -- links the two halves of one Offering entry
  deleted_at        TEXT,
  delete_reason     TEXT
);

CREATE TABLE settings (
  key   TEXT PRIMARY KEY,
  value TEXT
);

CREATE TABLE audit_log (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts          TEXT NOT NULL,
  action      TEXT NOT NULL,               -- CREATE, UPDATE, DELETE, RESTORE ...
  entity_type TEXT,
  entity_id   BIGINT,
  old_value   TEXT,
  new_value   TEXT,
  reason      TEXT,
  prev_hash   TEXT,                        -- hash chain: tampering breaks the chain
  hash        TEXT NOT NULL
);

CREATE INDEX idx_receipts_date ON receipts(receipt_date);
CREATE INDEX idx_lines_receipt ON receipt_lines(receipt_id);
CREATE INDEX idx_lines_item    ON receipt_lines(item_id);
CREATE INDEX idx_receipts_person ON receipts(person_id);

-- Seed data ---------------------------------------------------------------
INSERT INTO funds (id, name) VALUES (1, 'Trust Fund'), (2, 'Local Fund');
SELECT setval(pg_get_serial_sequence('funds', 'id'), (SELECT MAX(id) FROM funds));

INSERT INTO items (fund_id, name, system_key) VALUES
  (1, 'Tithe', NULL),
  (1, 'Campmeeting 13th Sabbath', NULL),
  (1, 'Hope Channel', NULL),
  (1, 'Kireka Hospital', NULL),
  (1, 'Prime Radio', NULL),
  (1, 'Offerings 50%', 'OFFERING_TRUST'),
  (2, 'Camp Expense', NULL),
  (2, 'Kanisa Ku Mutima', NULL),
  (2, 'Development', NULL),
  (2, 'Social and Welfare', NULL),
  (2, 'Evangelism', NULL),
  (2, 'Lunch', NULL),
  (2, 'Women Ministry', NULL),
  (2, 'Children Ministry', NULL),
  (2, 'Camp Food', NULL),
  (2, 'Ambassadors Club', NULL),
  (2, 'LCB 50%', 'OFFERING_LOCAL'),
  (2, 'Deacons', NULL),
  (2, 'Elders Fund', NULL),
  (2, 'Men Ministry', NULL);
